modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"
# issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="stevesminipouch"
version="${file.jarVersion}"
displayName="Steve's Mini Pouch"
# updateJSONURL="https://www.curseforge.com/members/melara1024/projects"
displayURL="https://www.curseforge.com/members/melara1024/projects"
logoFile="icon.png"
authors="Melara1024"
# displayTest="MATCH_VERSION"
description='''This mod allows you to increase or decrease the number of slots and switch between inventory functions.More information will be posted on the Wiki on GitHub.'''

[[dependencies.stevesminipouch]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.stevesminipouch]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
